# Site Settings
title:               TheSoulbiz
tagline:             SysAdmin's Playground
description:
baseurl:             #"/"
url:                 #"https://soulbiz.github.io"
github:
  url:               #"https://soulbiz.github.io"
author:
  name:              "Omar Asensio"
  email:             "thesoulbiz@gmail.com"
  twitter:           #"linux"
  instagram:         #"soulbiz"
  github:            "soulbiz"
  docker:            "soulbiz"
  linkedin:          "omar-asensio-romeu-0251566a"
navigation:
- title: Posts
  url: /blog
- title: About
  url: /about
- title: Contact
  url: /contact
- title: Friends
  url: /friends
- title: Tags
  url: /taglist
- title: Tag-Cloud
  url: /tagcloud

paginate:            5
disqus:              soulbiz

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
